
;;;;;/********************************************************************************************************//**
;;;;;* file    IIC_SLAVE_V100.asm
;;;;;* brief   IIC_SLAVE Code
;;;;;* version V1.00
;;;;;* date    07/25/2018
;;;;;* author  BSI
;;;;;*************************************************************************************************************
;;;;;*
;;;;;* <h2><center>Copyright (C) 2018 Best Solution electronics Inc. All rights reserved</center></h2>
;;;;;*
;;;;;************************************************************************************************************/
;;;;;/* Includes -----------------------------------------------------------------------------------------------*/
             #include "IIC_SLAVE.INC"
;;;;;/*---------------------------------------------------------------------------------------------------------*/
;;;;;/*

        PUBLIC   _IIC_SLAVE_INITIAL
        PUBLIC   _IIC_SLAVE
        PUBLIC	 _IIC_SLAVE_HALT_PREPARE
        PUBLIC   _IIC_SLAVE_HALT_WAKEUP
        PUBLIC   _IIC_SLAVE_RETURN_MAIN



#define SlaveMode       HTX
#define AddrMatch       HAAS
#define MasterRead  SRW
#define SlaveRecAck RXAK
DUMMY_READ  macro
        MOV A,IIC_DATA      ;DUMMY READ
        endm
SLAVE_SEND_ACK  macro           ;enable transmits acknowledge
        CLR TXAK
        endm
Slave_Tx_Mode   macro
        set SlaveMode           ;HTX
        endm
Slave_Rx_Mode   macro           ;receive mode (master write)
        clr SlaveMode           ;HTX
        endm

IF_AddrNotMatch_GOTO    macro   addr
        SNZ AddrMatch       ;0:read/write data 1:address match
        JMP addr
        endm

IF_WriteData_GOTO   macro   addr
        SNZ MasterRead  ;SRW=0:master wants to write data,SRW=1:master wants to read data
        JMP addr
        endm

IF_Master_Read_GOTO macro   addr
        SZ  SlaveMode   ;HTX
        JMP addr
        endm
IF_ACK_GOTO macro   addr
        SNZ SlaveRecAck ;RXAK
        JMP addr
        endm
;*********************************************************************



READ_PROC MACRO RAM,ADDR,IIC_RW_GOTO
        ifdef   ADDR
                MOV     A,RAM
                SUB     A,ADDR
                SZ      C
                JMP     IIC_RW_GOTO
        endif
        ENDM

WRITE_PROC MACRO RAM,ADDR,IIC_RW_GOTO
        ifdef   ADDR
                MOV     A,RAM
                SUB     A,ADDR
                SZ      C
                JMP     IIC_RW_GOTO
        endif
        ENDM


;*******************************************************************
RAMBANK 0 IIC_SLAVE_STANDARD_RW_RAM
IIC_SLAVE_STANDARD_RW_RAM       .SECTION  'DATA'
IIC_STACK   DB 2 DUP(?)
;*******************************************************************
ifdef   PBP
ROMBANK 0 IIC_SLAVE_STANDARD_RW_CODE
endif
IIC_SLAVE_STANDARD_RW_CODE    .SECTION  'CODE'
IIC_WRITE_ENTRY PROC
                MOV     A,MP1
                MOV     IIC_STACK[0],A
                MOV     A,BP
                MOV     IIC_STACK[1],A
                CLR     IIC_DATA_OUT
                WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FFH,WRITE_ADDR_0FFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FEH,WRITE_ADDR_0FEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FDH,WRITE_ADDR_0FDH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FCH,WRITE_ADDR_0FCH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FBH,WRITE_ADDR_0FBH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0FAH,WRITE_ADDR_0FAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F9H,WRITE_ADDR_0F9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F8H,WRITE_ADDR_0F8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F7H,WRITE_ADDR_0F7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F6H,WRITE_ADDR_0F6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F5H,WRITE_ADDR_0F5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F4H,WRITE_ADDR_0F4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F3H,WRITE_ADDR_0F3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F2H,WRITE_ADDR_0F2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F1H,WRITE_ADDR_0F1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0F0H,WRITE_ADDR_0F0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0EFH,WRITE_ADDR_0EFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0EEH,WRITE_ADDR_0EEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0EDH,WRITE_ADDR_0EDH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0ECH,WRITE_ADDR_0ECH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0EBH,WRITE_ADDR_0EBH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0EAH,WRITE_ADDR_0EAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E9H,WRITE_ADDR_0E9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E8H,WRITE_ADDR_0E8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E7H,WRITE_ADDR_0E7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E6H,WRITE_ADDR_0E6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E5H,WRITE_ADDR_0E5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E4H,WRITE_ADDR_0E4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E3H,WRITE_ADDR_0E3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E2H,WRITE_ADDR_0E2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E1H,WRITE_ADDR_0E1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0E0H,WRITE_ADDR_0E0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DFH,WRITE_ADDR_0DFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DEH,WRITE_ADDR_0DEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DDH,WRITE_ADDR_0DDH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DCH,WRITE_ADDR_0DCH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DBH,WRITE_ADDR_0DBH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0DAH,WRITE_ADDR_0DAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D9H,WRITE_ADDR_0D9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D8H,WRITE_ADDR_0D8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D7H,WRITE_ADDR_0D7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D6H,WRITE_ADDR_0D6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D5H,WRITE_ADDR_0D5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D4H,WRITE_ADDR_0D4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D3H,WRITE_ADDR_0D3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D2H,WRITE_ADDR_0D2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D1H,WRITE_ADDR_0D1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0D0H,WRITE_ADDR_0D0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CFH,WRITE_ADDR_0CFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CEH,WRITE_ADDR_0CEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CDH,WRITE_ADDR_0CDH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CCH,WRITE_ADDR_0CCH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CBH,WRITE_ADDR_0CBH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0CAH,WRITE_ADDR_0CAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C9H,WRITE_ADDR_0C9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C8H,WRITE_ADDR_0C8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C7H,WRITE_ADDR_0C7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C6H,WRITE_ADDR_0C6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C5H,WRITE_ADDR_0C5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C4H,WRITE_ADDR_0C4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C3H,WRITE_ADDR_0C3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C2H,WRITE_ADDR_0C2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C1H,WRITE_ADDR_0C1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0C0H,WRITE_ADDR_0C0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BFH,WRITE_ADDR_0BFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BEH,WRITE_ADDR_0BEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BDH,WRITE_ADDR_0BDH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BCH,WRITE_ADDR_0BCH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BBH,WRITE_ADDR_0BBH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0BAH,WRITE_ADDR_0BAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B9H,WRITE_ADDR_0B9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B8H,WRITE_ADDR_0B8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B7H,WRITE_ADDR_0B7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B6H,WRITE_ADDR_0B6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B5H,WRITE_ADDR_0B5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B4H,WRITE_ADDR_0B4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B3H,WRITE_ADDR_0B3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B2H,WRITE_ADDR_0B2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B1H,WRITE_ADDR_0B1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0B0H,WRITE_ADDR_0B0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0AFH,WRITE_ADDR_0AFH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0AEH,WRITE_ADDR_0AEH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0ADH,WRITE_ADDR_0ADH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0ACH,WRITE_ADDR_0ACH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0ABH,WRITE_ADDR_0ABH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0AAH,WRITE_ADDR_0AAH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A9H,WRITE_ADDR_0A9H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A8H,WRITE_ADDR_0A8H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A7H,WRITE_ADDR_0A7H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A6H,WRITE_ADDR_0A6H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A5H,WRITE_ADDR_0A5H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A4H,WRITE_ADDR_0A4H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A3H,WRITE_ADDR_0A3H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A2H,WRITE_ADDR_0A2H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A1H,WRITE_ADDR_0A1H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_0A0H,WRITE_ADDR_0A0H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09FH,WRITE_ADDR_09FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09EH,WRITE_ADDR_09EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09DH,WRITE_ADDR_09DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09CH,WRITE_ADDR_09CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09BH,WRITE_ADDR_09BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_09AH,WRITE_ADDR_09AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_099H,WRITE_ADDR_099H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_098H,WRITE_ADDR_098H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_097H,WRITE_ADDR_097H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_096H,WRITE_ADDR_096H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_095H,WRITE_ADDR_095H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_094H,WRITE_ADDR_094H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_093H,WRITE_ADDR_093H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_092H,WRITE_ADDR_092H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_091H,WRITE_ADDR_091H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_090H,WRITE_ADDR_090H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08FH,WRITE_ADDR_08FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08EH,WRITE_ADDR_08EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08DH,WRITE_ADDR_08DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08CH,WRITE_ADDR_08CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08BH,WRITE_ADDR_08BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_08AH,WRITE_ADDR_08AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_089H,WRITE_ADDR_089H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_088H,WRITE_ADDR_088H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_087H,WRITE_ADDR_087H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_086H,WRITE_ADDR_086H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_085H,WRITE_ADDR_085H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_084H,WRITE_ADDR_084H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_083H,WRITE_ADDR_083H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_082H,WRITE_ADDR_082H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_081H,WRITE_ADDR_081H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_080H,WRITE_ADDR_080H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07FH,WRITE_ADDR_07FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07EH,WRITE_ADDR_07EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07DH,WRITE_ADDR_07DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07CH,WRITE_ADDR_07CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07BH,WRITE_ADDR_07BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_07AH,WRITE_ADDR_07AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_079H,WRITE_ADDR_079H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_078H,WRITE_ADDR_078H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_077H,WRITE_ADDR_077H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_076H,WRITE_ADDR_076H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_075H,WRITE_ADDR_075H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_074H,WRITE_ADDR_074H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_073H,WRITE_ADDR_073H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_072H,WRITE_ADDR_072H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_071H,WRITE_ADDR_071H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_070H,WRITE_ADDR_070H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06FH,WRITE_ADDR_06FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06EH,WRITE_ADDR_06EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06DH,WRITE_ADDR_06DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06CH,WRITE_ADDR_06CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06BH,WRITE_ADDR_06BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_06AH,WRITE_ADDR_06AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_069H,WRITE_ADDR_069H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_068H,WRITE_ADDR_068H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_067H,WRITE_ADDR_067H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_066H,WRITE_ADDR_066H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_065H,WRITE_ADDR_065H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_064H,WRITE_ADDR_064H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_063H,WRITE_ADDR_063H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_062H,WRITE_ADDR_062H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_061H,WRITE_ADDR_061H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_060H,WRITE_ADDR_060H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05FH,WRITE_ADDR_05FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05EH,WRITE_ADDR_05EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05DH,WRITE_ADDR_05DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05CH,WRITE_ADDR_05CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05BH,WRITE_ADDR_05BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_05AH,WRITE_ADDR_05AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_059H,WRITE_ADDR_059H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_058H,WRITE_ADDR_058H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_057H,WRITE_ADDR_057H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_056H,WRITE_ADDR_056H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_055H,WRITE_ADDR_055H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_054H,WRITE_ADDR_054H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_053H,WRITE_ADDR_053H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_052H,WRITE_ADDR_052H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_051H,WRITE_ADDR_051H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_050H,WRITE_ADDR_050H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04FH,WRITE_ADDR_04FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04EH,WRITE_ADDR_04EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04DH,WRITE_ADDR_04DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04CH,WRITE_ADDR_04CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04BH,WRITE_ADDR_04BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_04AH,WRITE_ADDR_04AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_049H,WRITE_ADDR_049H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_048H,WRITE_ADDR_048H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_047H,WRITE_ADDR_047H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_046H,WRITE_ADDR_046H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_045H,WRITE_ADDR_045H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_044H,WRITE_ADDR_044H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_043H,WRITE_ADDR_043H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_042H,WRITE_ADDR_042H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_041H,WRITE_ADDR_041H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_040H,WRITE_ADDR_040H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03FH,WRITE_ADDR_03FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03EH,WRITE_ADDR_03EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03DH,WRITE_ADDR_03DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03CH,WRITE_ADDR_03CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03BH,WRITE_ADDR_03BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_03AH,WRITE_ADDR_03AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_039H,WRITE_ADDR_039H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_038H,WRITE_ADDR_038H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_037H,WRITE_ADDR_037H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_036H,WRITE_ADDR_036H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_035H,WRITE_ADDR_035H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_034H,WRITE_ADDR_034H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_033H,WRITE_ADDR_033H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_032H,WRITE_ADDR_032H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_031H,WRITE_ADDR_031H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_030H,WRITE_ADDR_030H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02FH,WRITE_ADDR_02FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02EH,WRITE_ADDR_02EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02DH,WRITE_ADDR_02DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02CH,WRITE_ADDR_02CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02BH,WRITE_ADDR_02BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_02AH,WRITE_ADDR_02AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_029H,WRITE_ADDR_029H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_028H,WRITE_ADDR_028H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_027H,WRITE_ADDR_027H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_026H,WRITE_ADDR_026H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_025H,WRITE_ADDR_025H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_024H,WRITE_ADDR_024H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_023H,WRITE_ADDR_023H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_022H,WRITE_ADDR_022H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_021H,WRITE_ADDR_021H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_020H,WRITE_ADDR_020H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01FH,WRITE_ADDR_01FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01EH,WRITE_ADDR_01EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01DH,WRITE_ADDR_01DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01CH,WRITE_ADDR_01CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01BH,WRITE_ADDR_01BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_01AH,WRITE_ADDR_01AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_019H,WRITE_ADDR_019H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_018H,WRITE_ADDR_018H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_017H,WRITE_ADDR_017H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_016H,WRITE_ADDR_016H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_015H,WRITE_ADDR_015H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_014H,WRITE_ADDR_014H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_013H,WRITE_ADDR_013H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_012H,WRITE_ADDR_012H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_011H,WRITE_ADDR_011H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_010H,WRITE_ADDR_010H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00FH,WRITE_ADDR_00FH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00EH,WRITE_ADDR_00EH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00DH,WRITE_ADDR_00DH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00CH,WRITE_ADDR_00CH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00BH,WRITE_ADDR_00BH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_00AH,WRITE_ADDR_00AH_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_009H,WRITE_ADDR_009H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_008H,WRITE_ADDR_008H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_007H,WRITE_ADDR_007H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_006H,WRITE_ADDR_006H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_005H,WRITE_ADDR_005H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_004H,WRITE_ADDR_004H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_003H,WRITE_ADDR_003H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_002H,WRITE_ADDR_002H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_001H,WRITE_ADDR_001H_GOTO
		WRITE_PROC IIC_DATA_INDEX,WRITE_ADDR_000H,WRITE_ADDR_000H_GOTO
        RX_NEXT_DATA:
                INC     IIC_DATA_INDEX
                JMP     END_IIC_RW
IIC_WRITE_ENTRY ENDP
;*******************************************************************




;*******************************************************************
IIC_PRE_READ PROC
                MOV     A,MP1
                MOV     IIC_STACK[0],A
                MOV     A,BP
                MOV     IIC_STACK[1],A
                CLR     IIC_DATA_OUT
;================================================================
        ;--------------------------------------------------
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FFH,READ_ADDR_0FFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FEH,READ_ADDR_0FEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FDH,READ_ADDR_0FDH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FCH,READ_ADDR_0FCH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FBH,READ_ADDR_0FBH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0FAH,READ_ADDR_0FAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F9H,READ_ADDR_0F9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F8H,READ_ADDR_0F8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F7H,READ_ADDR_0F7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F6H,READ_ADDR_0F6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F5H,READ_ADDR_0F5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F4H,READ_ADDR_0F4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F3H,READ_ADDR_0F3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F2H,READ_ADDR_0F2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F1H,READ_ADDR_0F1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0F0H,READ_ADDR_0F0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0EFH,READ_ADDR_0EFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0EEH,READ_ADDR_0EEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0EDH,READ_ADDR_0EDH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0ECH,READ_ADDR_0ECH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0EBH,READ_ADDR_0EBH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0EAH,READ_ADDR_0EAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E9H,READ_ADDR_0E9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E8H,READ_ADDR_0E8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E7H,READ_ADDR_0E7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E6H,READ_ADDR_0E6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E5H,READ_ADDR_0E5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E4H,READ_ADDR_0E4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E3H,READ_ADDR_0E3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E2H,READ_ADDR_0E2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E1H,READ_ADDR_0E1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0E0H,READ_ADDR_0E0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DFH,READ_ADDR_0DFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DEH,READ_ADDR_0DEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DDH,READ_ADDR_0DDH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DCH,READ_ADDR_0DCH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DBH,READ_ADDR_0DBH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0DAH,READ_ADDR_0DAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D9H,READ_ADDR_0D9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D8H,READ_ADDR_0D8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D7H,READ_ADDR_0D7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D6H,READ_ADDR_0D6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D5H,READ_ADDR_0D5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D4H,READ_ADDR_0D4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D3H,READ_ADDR_0D3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D2H,READ_ADDR_0D2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D1H,READ_ADDR_0D1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0D0H,READ_ADDR_0D0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CFH,READ_ADDR_0CFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CEH,READ_ADDR_0CEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CDH,READ_ADDR_0CDH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CCH,READ_ADDR_0CCH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CBH,READ_ADDR_0CBH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0CAH,READ_ADDR_0CAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C9H,READ_ADDR_0C9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C8H,READ_ADDR_0C8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C7H,READ_ADDR_0C7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C6H,READ_ADDR_0C6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C5H,READ_ADDR_0C5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C4H,READ_ADDR_0C4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C3H,READ_ADDR_0C3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C2H,READ_ADDR_0C2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C1H,READ_ADDR_0C1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0C0H,READ_ADDR_0C0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BFH,READ_ADDR_0BFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BEH,READ_ADDR_0BEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BDH,READ_ADDR_0BDH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BCH,READ_ADDR_0BCH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BBH,READ_ADDR_0BBH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0BAH,READ_ADDR_0BAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B9H,READ_ADDR_0B9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B8H,READ_ADDR_0B8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B7H,READ_ADDR_0B7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B6H,READ_ADDR_0B6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B5H,READ_ADDR_0B5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B4H,READ_ADDR_0B4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B3H,READ_ADDR_0B3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B2H,READ_ADDR_0B2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B1H,READ_ADDR_0B1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0B0H,READ_ADDR_0B0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0AFH,READ_ADDR_0AFH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0AEH,READ_ADDR_0AEH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0ADH,READ_ADDR_0ADH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0ACH,READ_ADDR_0ACH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0ABH,READ_ADDR_0ABH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0AAH,READ_ADDR_0AAH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A9H,READ_ADDR_0A9H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A8H,READ_ADDR_0A8H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A7H,READ_ADDR_0A7H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A6H,READ_ADDR_0A6H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A5H,READ_ADDR_0A5H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A4H,READ_ADDR_0A4H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A3H,READ_ADDR_0A3H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A2H,READ_ADDR_0A2H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A1H,READ_ADDR_0A1H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_0A0H,READ_ADDR_0A0H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09FH,READ_ADDR_09FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09EH,READ_ADDR_09EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09DH,READ_ADDR_09DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09CH,READ_ADDR_09CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09BH,READ_ADDR_09BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_09AH,READ_ADDR_09AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_099H,READ_ADDR_099H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_098H,READ_ADDR_098H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_097H,READ_ADDR_097H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_096H,READ_ADDR_096H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_095H,READ_ADDR_095H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_094H,READ_ADDR_094H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_093H,READ_ADDR_093H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_092H,READ_ADDR_092H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_091H,READ_ADDR_091H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_090H,READ_ADDR_090H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08FH,READ_ADDR_08FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08EH,READ_ADDR_08EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08DH,READ_ADDR_08DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08CH,READ_ADDR_08CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08BH,READ_ADDR_08BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_08AH,READ_ADDR_08AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_089H,READ_ADDR_089H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_088H,READ_ADDR_088H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_087H,READ_ADDR_087H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_086H,READ_ADDR_086H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_085H,READ_ADDR_085H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_084H,READ_ADDR_084H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_083H,READ_ADDR_083H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_082H,READ_ADDR_082H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_081H,READ_ADDR_081H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_080H,READ_ADDR_080H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07FH,READ_ADDR_07FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07EH,READ_ADDR_07EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07DH,READ_ADDR_07DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07CH,READ_ADDR_07CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07BH,READ_ADDR_07BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_07AH,READ_ADDR_07AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_079H,READ_ADDR_079H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_078H,READ_ADDR_078H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_077H,READ_ADDR_077H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_076H,READ_ADDR_076H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_075H,READ_ADDR_075H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_074H,READ_ADDR_074H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_073H,READ_ADDR_073H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_072H,READ_ADDR_072H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_071H,READ_ADDR_071H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_070H,READ_ADDR_070H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06FH,READ_ADDR_06FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06EH,READ_ADDR_06EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06DH,READ_ADDR_06DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06CH,READ_ADDR_06CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06BH,READ_ADDR_06BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_06AH,READ_ADDR_06AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_069H,READ_ADDR_069H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_068H,READ_ADDR_068H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_067H,READ_ADDR_067H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_066H,READ_ADDR_066H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_065H,READ_ADDR_065H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_064H,READ_ADDR_064H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_063H,READ_ADDR_063H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_062H,READ_ADDR_062H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_061H,READ_ADDR_061H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_060H,READ_ADDR_060H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05FH,READ_ADDR_05FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05EH,READ_ADDR_05EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05DH,READ_ADDR_05DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05CH,READ_ADDR_05CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05BH,READ_ADDR_05BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_05AH,READ_ADDR_05AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_059H,READ_ADDR_059H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_058H,READ_ADDR_058H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_057H,READ_ADDR_057H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_056H,READ_ADDR_056H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_055H,READ_ADDR_055H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_054H,READ_ADDR_054H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_053H,READ_ADDR_053H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_052H,READ_ADDR_052H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_051H,READ_ADDR_051H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_050H,READ_ADDR_050H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04FH,READ_ADDR_04FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04EH,READ_ADDR_04EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04DH,READ_ADDR_04DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04CH,READ_ADDR_04CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04BH,READ_ADDR_04BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_04AH,READ_ADDR_04AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_049H,READ_ADDR_049H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_048H,READ_ADDR_048H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_047H,READ_ADDR_047H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_046H,READ_ADDR_046H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_045H,READ_ADDR_045H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_044H,READ_ADDR_044H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_043H,READ_ADDR_043H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_042H,READ_ADDR_042H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_041H,READ_ADDR_041H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_040H,READ_ADDR_040H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03FH,READ_ADDR_03FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03EH,READ_ADDR_03EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03DH,READ_ADDR_03DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03CH,READ_ADDR_03CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03BH,READ_ADDR_03BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_03AH,READ_ADDR_03AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_039H,READ_ADDR_039H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_038H,READ_ADDR_038H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_037H,READ_ADDR_037H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_036H,READ_ADDR_036H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_035H,READ_ADDR_035H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_034H,READ_ADDR_034H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_033H,READ_ADDR_033H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_032H,READ_ADDR_032H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_031H,READ_ADDR_031H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_030H,READ_ADDR_030H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02FH,READ_ADDR_02FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02EH,READ_ADDR_02EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02DH,READ_ADDR_02DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02CH,READ_ADDR_02CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02BH,READ_ADDR_02BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_02AH,READ_ADDR_02AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_029H,READ_ADDR_029H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_028H,READ_ADDR_028H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_027H,READ_ADDR_027H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_026H,READ_ADDR_026H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_025H,READ_ADDR_025H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_024H,READ_ADDR_024H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_023H,READ_ADDR_023H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_022H,READ_ADDR_022H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_021H,READ_ADDR_021H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_020H,READ_ADDR_020H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01FH,READ_ADDR_01FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01EH,READ_ADDR_01EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01DH,READ_ADDR_01DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01CH,READ_ADDR_01CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01BH,READ_ADDR_01BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_01AH,READ_ADDR_01AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_019H,READ_ADDR_019H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_018H,READ_ADDR_018H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_017H,READ_ADDR_017H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_016H,READ_ADDR_016H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_015H,READ_ADDR_015H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_014H,READ_ADDR_014H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_013H,READ_ADDR_013H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_012H,READ_ADDR_012H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_011H,READ_ADDR_011H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_010H,READ_ADDR_010H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00FH,READ_ADDR_00FH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00EH,READ_ADDR_00EH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00DH,READ_ADDR_00DH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00CH,READ_ADDR_00CH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00BH,READ_ADDR_00BH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_00AH,READ_ADDR_00AH_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_009H,READ_ADDR_009H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_008H,READ_ADDR_008H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_007H,READ_ADDR_007H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_006H,READ_ADDR_006H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_005H,READ_ADDR_005H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_004H,READ_ADDR_004H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_003H,READ_ADDR_003H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_002H,READ_ADDR_002H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_001H,READ_ADDR_001H_GOTO
                READ_PROC IIC_DATA_INDEX,READ_ADDR_000H,READ_ADDR_000H_GOTO


                ifdef   READ_ADDR_000H
                RW_ADDR_000H:
                        ifdef READ_ADDR_00H_GOTO
                                SZ      IIC_DATA_INDEX
                                JMP     END_IIC_RW
                                JMP     READ_ADDR_00H
                        endif
                END_RW_ADDR_000H:
                endif

                ;--------------------------------------------------
                TX_00H:
                        CLR     IIC_DATA_OUT
                        JMP     END_IIC_RW
                ;-IIC PRE-LOAD DATA
                TX_IAR1:
                        MOV     BP,A
                        MOV     A,IAR1
                TX_ACC:
                        MOV     IIC_DATA_OUT,A
                ;--------------------------------------------------
;================================================================
END_IIC_RW:
                MOV     A,IIC_STACK[1]
                MOV     BP,A
                MOV     A,IIC_STACK[0]
                MOV     MP1,A
                JMP     _ENDIIC
IIC_PRE_READ ENDP
;*******************************************************************



;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
;*************************************************************************************************************************************************
RAMBANK 0 IIC_SLAVE_STANDARD_RAM
IIC_SLAVE_STANDARD_RAM       .SECTION  'DATA'
ifdef   PBP
IIC_INT_STACK       DB 3 DUP(?)
else
IIC_INT_STACK       DB 2 DUP(?)
endif
bWrite1st       DBIT
IIC_DATA_OUT    DB      ?
IIC_DATA_IN     DB      ?
IIC_DATA_INDEX  DB      ?
;=====================================================================


;*********************************************************************
ifdef   PBP
ROMBANK 0 IIC_INT_CODE
endif
IIC_INT_CODE   .SECTION  AT IIC_INT_ADDR 'CODE'
                MOV     IIC_INT_STACK[0],A
        ifdef   PBP
                MOV     A,PBP
                CLR     PBP
        endif
                JMP     IIC_INT

IIC_SLAVE_STANDARD_CODE    .SECTION  'CODE'
IIC_INITIAL PROC
;JMP    IIC_WRITE_ENTRY
;jmp    IIC_PRE_READ

        IIC_SDA_PU
        IIC_SCL_PU
        IIC_SDA_PIN
        IIC_SCL_PIN
	SET	EMI
        ;--
        MOV     A,11000010B ;IIC Mode ,Enable SIM
        MOV     IIC_INT_CTRL,A

        MOV     A,IIC_ADDRESS
        MOV     IIC_ADDR,A

        CLR     HTX
        CLR     TXAK
        SET     IIC_ADDR_MATCH_WAKEUP
        ;--
        CLR     IIC_INT_FLG        ;Clear SIM interrupt request flag

        MOV     A,10111111B ;Enable IIC Time-out Countrol
        MOV     IIC_TimeOutCtrl,A              ;IIC time-out time is 64*32/32K = 62.5mSec

        SET     IIC_INT_ENABLE

        RET
IIC_INITIAL ENDP

;*******************************************************************
_IIC_SLAVE:
        SZ      IIC_TimeOut
        CALL    IIC_INITIAL

ifdef   IIC_SLAVE_STANDARD_FUNCTION
        JMP     IIC_SLAVE_STANDARD_FUNCTION
else
        RET
endif
;*******************************************************************

;*******************************************************************
_IIC_SLAVE_INITIAL:
        CALL    IIC_INITIAL
ifdef   IIC_SLAVE_STANDARD_INITIAL
        JMP     IIC_SLAVE_STANDARD_INITIAL
else
        RET
endif

;*******************************************************************
;*********************************************************************
;;***********************************************************
;;*SUB. NAME:                                               *
;;*INPUT    :                                               *
;;*OUTPUT   :                                               *
;;*USED REG.:                                               *
;;*FUNCTION :                                               *
;;***********************************************************
                ;;*******************
IIC_INT:        ;;* IIC INT. ********
                ;;*******************
        ifdef  PBP
                MOV     IIC_INT_STACK[2],A
        endif
                MOV     A,STATUS
                MOV     IIC_INT_STACK[1],A
        ifdef   IIC_IS_MF_INT
                SNZ     IIC_INT_FLG
                JMP     _ENDIIC
                CLR     IIC_INT_FLG
        endif
        ifdef   IIC_INT_EXECUTE
                JMP	IIC_INT_EXECUTE
        IIC_INT_EXECUTE_END:
	endif
                ;-CHECK IF ADDRESS MATCH
                IF_AddrNotMatch_GOTO    IIC_CONTINUE_RW
                IF_WriteData_GOTO   FIRST_WRITE
                ;-FIRST READ (PREPARE DATA) SRW=1
                Slave_Tx_Mode
                JMP     IIC_CONTINUE_READ
    IIC_CONTINUE_RW:
                IF_Master_Read_GOTO IIC_MASTER_READ
                ;-HTX=0 MASTER WRITE
                MOV     A,IIC_DATA
                MOV     IIC_DATA_IN,A
                SZ      bWrite1st
                JMP     IIC_WRITE_ENTRY
                ;JMP     _ENDIIC
                MOV     IIC_DATA_INDEX,A    ;-GET 1ST BYTE (ADDRESS)
                SET     bWrite1st
                JMP     IIC_PRE_READ    ;PR-READ DATA
    FIRST_WRITE:;SRW=0
                CLR     bWrite1st
                JMP     SIM_RECEIVE_MODE
    IIC_MASTER_READ:
                IF_ACK_GOTO IIC_CONTINUE_READ
                ;NACK
    SIM_RECEIVE_MODE:
                Slave_Rx_Mode       ;receive mode (master write)
                SLAVE_SEND_ACK      ;enable transmits acknowledge
                DUMMY_READ
    _ENDIIC:
        ifdef   PBP
                MOV     A,IIC_INT_STACK[2]
                MOV     PBP,A
        endif
                MOV     A,IIC_INT_STACK[1]
                MOV     STATUS,A
                MOV     A,IIC_INT_STACK[0]
                RETI
;*******************************************************************
IIC_CONTINUE_READ:
        MOV     A,IIC_DATA_OUT
        MOV     IIC_DATA,A
        INC     IIC_DATA_INDEX
        JMP     IIC_PRE_READ
;*******************************************************************
message '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - '
;;;;;*/
